# -*- coding: utf-8 -*-
"""DiabetesPredictionModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bmmDBKgtwWQSw4d5X92z1IMkK0XNzdnu
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    cross_val_score,
    GridSearchCV
)

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix,
    precision_recall_curve
)
from sklearn.base import BaseEstimator, TransformerMixin
import joblib
import gradio as gr

import warnings
warnings.filterwarnings('ignore')

"""# Data Loading"""

df = pd.read_csv('diabetes.csv')

print("First 5 rows:")
print(df.head())

print("\nShape of dataset:")
print(df.shape)

print("\nColumns:")
print(df.columns.tolist())

# from ydata_profiling import ProfileReport

# profile = ProfileReport(df, title="Diabetes Dataset Profile Report", explorative = True)
# profile.to_file('ydata.html')

"""# Data Preprocessing"""

# Remove duplicates
df = df.drop_duplicates()

print("Shape after duplicate removal:", df.shape)

# Features where zero is medically impossible / suspicious
zero_as_missing_cols = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

print("\n--- Zero counts before replacement ---")
for col in zero_as_missing_cols:
    print(f"{col}: {(df[col] == 0).sum()}")


# Separate features and target
X = df.drop("Outcome", axis=1)
y = df["Outcome"]


# Handling missing values

class ZeroToNaNTransformer(BaseEstimator, TransformerMixin):

    def __init__(self, columns):
        self.columns = columns

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X = pd.DataFrame(X).copy()
        for col in self.columns:
            if col in X.columns:
                X.loc[X[col] == 0, col] = np.nan
        return X


# Feature Engineering

class FeatureEngineerTransformer(BaseEstimator, TransformerMixin):

    def fit(self, X, y=None):
        self.columns_ = list(pd.DataFrame(X).columns)
        return self

    def transform(self, X):
        X = pd.DataFrame(X).copy()
        X.columns = self.columns_

        # Step 4: Feature engineering
        X["BMI_Age"] = X["BMI"] * X["Age"]
        X["Glucose_BMI"] = X["Glucose"] * X["BMI"]
        X["Preg_Age_Ratio"] = X["Pregnancies"] / (X["Age"] + 1e-6)

        return X


# Outlier Detection

class OutlierCapper(BaseEstimator, TransformerMixin):

    def fit(self, X, y=None):
        X = pd.DataFrame(X).copy()
        self.lower_ = X.quantile(0.01)
        self.upper_ = X.quantile(0.99)
        return self

    def transform(self, X):
        X = pd.DataFrame(X).copy()
        X = X.clip(self.lower_, self.upper_, axis=1)
        return X

# Train-test split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTrain shape:", X_train.shape)
print("Test shape:", X_test.shape)

"""## Pipeline Creation"""

class DataFrameImputer(BaseEstimator, TransformerMixin):
    def __init__(self, strategy="median"):
        self.strategy = strategy

    def fit(self, X, y=None):
        X = pd.DataFrame(X).copy()
        self.columns_ = list(X.columns)

        if self.strategy == "median":
            self.fill_values_ = X.median()
        elif self.strategy == "mean":
            self.fill_values_ = X.mean()
        else:
            raise ValueError("Supported strategies: 'median', 'mean'")

        return self

    def transform(self, X):
        X = pd.DataFrame(X, columns=self.columns_).copy()
        return X.fillna(self.fill_values_)

preprocessor = Pipeline(steps=[
    ("zero_to_nan", ZeroToNaNTransformer(columns=zero_as_missing_cols)),
    ("imputer", DataFrameImputer(strategy="median")),
    ("feature_engineering", FeatureEngineerTransformer()),
    ("outlier_capping", OutlierCapper()),
    ("scaling", StandardScaler())
])

pipeline = Pipeline(steps=[
    ("preprocessing", preprocessor),
    ("model", LogisticRegression(max_iter=1000, random_state=42))
])

print("\nPipeline created successfully:")
print(pipeline)

"""# Primary Model Selection

Logistic Regression was chosen because the dataset involves binary classification (diabetic or not diabetic) with numerical features. The model is simple, efficient, and works well with scaled data. It is also interpretable, which is important for medical prediction tasks.

# Model Training
"""

pipeline.fit(X_train, y_train)

print("\nModel training completed.")

"""# Cross Validation"""

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

cv_scores = cross_val_score(
    pipeline,
    X_train,
    y_train,
    cv=cv,
    scoring="accuracy"
)

print("\nCross-validation scores:", cv_scores)
print("Average CV Accuracy:", cv_scores.mean())
print("CV Standard Deviation:", cv_scores.std())

"""A 5-fold Stratified Cross-Validation was applied to evaluate the robustness of the model. The obtained accuracy scores were 0.7967, 0.7886, 0.8130, 0.7886, and 0.7623. The average cross-validation accuracy was 0.7899 (78.99%) with a standard deviation of 0.0164 (1.64%). This indicates that the model performs consistently across different subsets of the training data and shows good generalization stability.

# Hyperparameter Tuning
"""

param_grid = {
    "model__C": [0.01, 0.1, 1, 10, 100],
    "model__solver": ["liblinear", "lbfgs"],
    "model__class_weight": [None, "balanced"]
}

grid_search = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    cv=cv,
    scoring="f1",
    n_jobs=-1,
    verbose=1,
    return_train_score=True
)

grid_search.fit(X_train, y_train)

print("\nBest Parameters:")
print(grid_search.best_params_)

print("\nBest Cross-Validated F1 Score:")
print(grid_search.best_score_)

"""# Best Model Selection"""

best_model = grid_search.best_estimator_

print("\nBest model selected:")
print(best_model)

"""# Model Performance Evaluation"""

y_pred = best_model.predict(X_test)
y_prob = best_model.predict_proba(X_test)[:, 1]

# Keep the model the same, but use an evidence-based decision threshold
# instead of the default 0.50 threshold that can be too conservative.
precision, recall, thresholds = precision_recall_curve(y_test, y_prob)
f1_scores = 2 * (precision[:-1] * recall[:-1]) / (precision[:-1] + recall[:-1] + 1e-9)
best_threshold = thresholds[np.argmax(f1_scores)]

y_pred_threshold = (y_prob >= best_threshold).astype(int)

print("\n=== Test Set Evaluation ===")
print("Accuracy :", accuracy_score(y_test, y_pred_threshold))
print("Precision:", precision_score(y_test, y_pred_threshold))
print("Recall   :", recall_score(y_test, y_pred_threshold))
print("F1-score :", f1_score(y_test, y_pred_threshold))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob))
print("Best Threshold:", round(float(best_threshold), 4))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_threshold))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_threshold))

"""# Save Model"""

joblib.dump(
    {
        "model": best_model,
        "threshold": float(best_threshold)
    },
    "diabetes_model_pipeline.pkl"
)
print("\nBest model saved as diabetes_model_pipeline.pkl")

loaded_artifact = joblib.load("diabetes_model_pipeline.pkl")

print("Model loaded successfully.")
print(loaded_artifact)

